"$schema" = 'https://starship.rs/config-schema.json'

[username]
show_always = false
style_user = "bold yellow"
format = "[$user]($style)@"

[hostname]
ssh_only = true
style = "bold yellow"
format = "[$hostname]($style) "

[docker_context]
disabled = true

[container]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false
